glider_dac/views/user.py
Removes action from user edit form, causing the form to render action
attribute as "".  This fixes some http redirection issues in #104, but
ultimately, a way to always use https:// scheme on the production
settings should eventually be found.
=> Removes action from user edit form

scripts/replicatePrivateErddapDeployments.py
Handles failure cases in aiohttp, i.e. non success HTTP codes.
Writes initial file to temp file prior to overwriting previous file
Also adds error checking for netCDF file downloaded by attempting to open
file.  If it's corrupt, the file won't get written.
=> Handle failures in aiohttp

glider_util/bdb.py, requirements.txt
Uses passlib's SHA512 encryption to encrypt/verify passwords stored
in BerkeleyDB, rather than storing them in plaintext, which is a security risk.
Important note:  If using pam_userdb as an auth provider to vsftpd, ensure
the following lines are present in the PAM configuration for vsftpd,
where <USER_DB_LOC> is the location of the BerkeleyDB user database:
auth    required    pam_userdb.so db=<USER_DB_LOC> crypt=crypt
account required    pam_userdb.so db=<USER_DB_LOC> crypt=crypt
session required    pam_loginuid.so
=> Use passlib to encrypt passwords with SHA512

glider_dac/glider_emails.py, glider_dac/models/deployment.py, requirements.txt, scripts/archive_datasets.py, scripts/run_checker_emails.py
- Refactors main glider check code to move to main repo rather than `scripts` folder.
- Modifies archival logic for deployments to require a passing glider check in addition to being marked as completed and ready for NCEI archival.
- Use update statements to MongoDB `on_complete` (which is misleadingly named, should be more like `on_sync_data`).  Also use `update` on queued compliance checks.  This prevents an issue where `save` could overwrite the results of a run compliance check and the check results would not get written.
=> Glider check email update

scripts/build_erddap_catalog.py, scripts/glider_qartod.py, scripts/replicatePrivateErddapDeployments.py
Stops delayed mode dataset replication and QC.  Adds delayed mode
attribute to glider template.  Reduces async semaphore count for
replication from 8 to 2.
=> Temporarily stop delayed mode processing

scripts/build_erddap_catalog.py
Fixes problems passing delayed mode status to templates (curently unused, but may be useful in future iterations)
=> Properly handle delayed mode before passing to templates

scripts/build_erddap_catalog.py
Fixes an issue under Python 3 where a file expected string/unicode to be
written, but fails because etree.tostring returns bytes by default.
Updated code adds the encoding argument to etree.tostring, fixing this
issue.
=> Fixes error with datasets snippet where str expected

scripts/replicatePrivateErddapDeployments.py, scripts/sync_erddap_datasets.py
@benjwadams turns out `os.path.getmtime(0)` returns the current time in python 3. Better than an exception but not what we're looking for here. Basically we end up asking ERDDAP to update deployments with no files.
The removing of `import datetime` is because we use `from datetime import datetime` below that.
=> Fix bug in get_mod_time logic

scripts/build_erddap_catalog.py
Fixes a unicode issue with slugify method under Py3 where a string was cast
to bytes.
=> Hotfix for Py3 slugify method

docker-compose.yml, glider_dac/views/deployment.py
Will create glider deployments with same glider identifier (e.g. "ru30"), and time, but differing delayed mode vs real time settings. Thus, the following scenarios will work:
- Real-time dataset exists and marked as completed, delayed mode creation
(same as marking existing deployment as delayed mode)
- Delayed mode dataset exists and marked as completed, real-time creation
- Same mode for both existing dataset and desired created deployment
will fail, since the unique deployment name already exists
- Delayed or real-time mode with no pre-existing deployments will create
deployments as usual.
=> Create deployment if mode differs but callsign/date is same

glider_dac/models/deployment.py
@benjwadams this causes issues with the watchdog script and theres no way for users to edit wmoid from the form.
=> Dont write wmoid.txt on every save

glider_qc/glider_qc.py
=> Revert "Update QARTOD flags to use non-deprecated standard names"

scripts/build_erddap_catalog.py
Removes all subset variables from datasets except for profile_id, time, latitude, and longitude.
Addresses https://github.com/ioos/ioosngdac/issues/156.
=> Remove subset variables from datasets.xml

.github/dependabot.yml, .github/workflows/md-link-check.yml, .github/workflows/mlc_config.json, .pre-commit-config.yaml, README.md, glider_dac/models/deployment.py, glider_dac_watchdog.py, scripts/build_erddap_catalog.py, scripts/download_waf.py, scripts/replicatePrivateErddapDeployments.py, scripts/sync_erddap_datasets.py
Just codespell, that will be useful in the gh-pages, large files, and link check.
Closes https://github.com/ioos/glider-dac/issues/256
=> add pre-commits

README.md
Disables markdown-link-check on README.md file in section describing local development setup referring to localhost:3000.
=> Disable markdown-link-check on localhost

scripts/build_erddap_catalog.py
Changes to writing datasets.xml in place by first placing the XML contents to a memory buffer and then writing the buffer to datasets.xml when finished.  This prevents issues wherein the datasets.xml might contain invalid contents or fail while writing, leaving an invalid XML document. ERDDAP datasets.xml documentation say it's fine to write directly to the file as well, assuming well-formedness.  Also addresses issues related to Docker bind mounts which may have arose in 7d5bd4bbf5012c9ae854b4292ab14d7fa2bc5605 where copying a file over would result in the old copy being kept due to references to the old inodes.
=> Write datasets.xml in place

glider_dac/templates/show_deployment.html
Improves situation for #349 by adding WMO IDs to page detail.
=> Add WMO ID display to glider deployment detail page

scripts/build_erddap_catalog.py
More or less preserves existing QARTOD behavior for existing real-time data -- keeps these variables if they exist, but now uses some logic to keep those attributes.  Automatic QC variable creation and associated QARTOD variables will still be kept where QARTOD is not provided.
For delayed mode, only include QARTOD variables if they exist for within the datasets.
cc: @kerfoot
=> Exclude QARTOD variables not provided by user for delayed mode datasets.xml

glider_dac/glider_emails.py
Adds an email template to notify users/providers of deployments that are not marked as completed and have not seen updates for over two weeks.
=> Email for non completed glider deployments

scripts/replicatePrivateErddapDeployments.py
Re-enables replication of delayed mode datasets for later archival. Previously disabled in dc245bd.
=> Allow replication/aggregation of delayed mode datasets

glider_dac/glider_emails.py, glider_dac/models/deployment.py, glider_dac/worker.py, glider_qc/glider_qc.py
Moves compliance checks on deployments to jobs scheduled half an hour in the future.  If, on further invocations of checking if the compliance check passed, if it is found that there is already a job scheduled in the future for a particular deployment, the compliance check is not scheduled again.  This cuts down on duplication of jobs and the associated processing overhead due to many detected file events while also allowing for conditions such as deployment data resubmission to be handled.
=> Pass compliance checking to scheduled jobs

config.yml, glider_dac/__init__.py, glider_qc/glider_qc.py, requirements.txt
Updates to use a stable version of ioos_qc on PyPI, makes several code changes to accommodate interface changes.
=> Update QC Requirements

.github/workflows/sync_theme.yml, Dockerfile, glider_qc/glider_qc.py, requirements.txt, tests/test_glider_qc.py
Support ioos_qc v2.2.0 by removing some incompatible typing information.  This is a heavy workaround and merging the PR in #424 to update the Python version should absolutely be preferred to removing typing information.  Hence, the portion of this PR which performs substitution to remove the typing annotations should be reverted once that PR is merged.
=> Fix IOOS QARTOD legacy update

_docs/ngdac-netcdf-file-format-version-2.md, _docs/ngdac-netcdf-file-submission-process.md
This update clarifies variable-level GTS ingestion by specifying that adding gts_ingest = "false" to a variable’s attributes will exclude it from GTS ingest. Previously, the text implied that each variable needed a gts_ingest attribute to be sent, which caused confusion.
=> Configuring gts_ingest Attributes for GTS Ingestion
