- glider_dac/__init__.py
- glider_dac/defaults.py
- glider_dac/views/deployment.py
- glider_dac/views/index.py
- glider_dac/views/user.py
This reverts commit 6bb4db811175606ad80455082d3f110a370ce2c4, reversing
changes made to 1482966b3316724f4569d3043bb113a513ab4061.
> Revert "Merge pull request #50 from lukecampbell/prefix"

- glider_dac/__init__.py
- glider_dac/models/deployment.py
- glider_dac/templates/index.html
- glider_dac/templates/user_deployments.html
- glider_dac/views/deployment.py
- glider_dac/views/index.py
- migrations/20150731-glider-name.py
- migrations/migration.py
- requirements.txt
- Adds migrations for the two new fields
- Adds regex validation to glider name and date
- Removes "recent uploads" section of index for performance
- Adds server-side session management
> Adds separates deployment name into name and date

- glider_dac/models/deployment.py
- glider_dac_db_sync.py
- scripts/build_erddap_catalog.py
This requires https://github.com/ioos/ioosngdac/pull/86.
> Attempt to track a checksum for a given Deployment

- glider_dac/views/deployment.py
Fixes operator path so that slashes will not cause URL to fail.
> Fixes operator path

- glider_qc/glider_qc.py
- tests/test_glider_qc.py
@lukecampbell calculates the threshold value to use in rate of change test
> Calculate rate of change threshold values

- data/qc_config.yml
- glider_qc/glider_qc.py
@lukecampbell please review
Calculates spike test thresholds and uses new qartod spike test that respects time gaps. Depends on https://github.com/ioos/qartod/pull/12
> Update glider qc threshold values

- glider_dac/models/deployment.py
- glider_dac/templates/index.html
- glider_dac/views/index.py
- By removing some unneeded and buggy sections of the UI we can improve
loading times dramatically!
- Also the code was in dire need of some PEP-8ing
> Cleans up the code and improves performance

- scripts/replicatePrivateErddapDeployments.py
@kerfoot this is what I need to increase the frequency of the replication process.
> Adds file lock to replicate process

- scripts/archive_datasets.py
> Revert "Do not remove archive file"

- scripts/build_erddap_catalog.py
Sets _FillValue equal to -127 for any variables ending with `_qc` when
the attribute has not already been defined.
Automatically sets attributes for variables beginning with the string
`qartod`.  Variables automatically set are `flag_values`, `flag_meanings`,
and `_FillValue` (set to 2/NOT_EVALUATED, indicated QC has yet to be
performed)
Changes variables passed to template.  This is a breaking change and
requires the new templates.
> Adds attributes to QC variables

- scripts/replicatePrivateErddapDeployments.py
> Reduce number of retries and lower sleep

- .gitignore
- glider_dac/models/deployment.py
- glider_dac/templates/macros.html
- glider_dac/templates/user_deployments.html
- glider_dac/views/deployment.py
@benjwadams please review/test
> Delayed mode

- scripts/replicatePrivateErddapDeployments.py
Note: much faster than the original code, but **requires Python >= 3.5**
> Async replicate erddap wip

- scripts/build_erddap_catalog.py
@kerfoot this ensures that a proper dataset.xml file is generated
> Add more error checking to build_erddap_catalog

- glider_dac/models/deployment.py
- glider_dac_db_sync.py
Updates filesystem watcher logic to properly sync/update
necessary files/models when a file is rsynced.
> Updates watcher logic

- scripts/build_erddap_catalog.py
Allows users to create attributes in private ERDDAP datasets.xml with a
JSON file named extra_atts.json placed in the datasets directory.
> Allows user-defined attributes in datasets.xml

- requirements.txt
- scripts/build_erddap_catalog.py
Adds standard name variables to ERDDAP templates
> Add standard name vars

- glider_dac/views/deployment.py
Fixes key arg to sorted() by replacing call to cmp with single arg lambda functions.
> Fix key arg to sorted

- glider_dac/models/user.py
- glider_dac/templates/admin.html
- glider_dac/views/deployment.py
Makes is_admin method function a property.  Fixes an issue where logged
in non-admin users could see admin panel due to is_admin was called
without parentheses in a way similar to other flask-login methods and
would return a truthy value from returning the method rather than a boolean.
> Make is_admin a property

- glider_dac/erddap/templates/private/dataset.deployment.xml
- scripts/replicatePrivateErddapDeployments.py
- scripts/sync_erddap_datasets.py
Split replicatePrivateErddapDeployment script in 2, create sync_erddap_datasets, update datasets.xml template to disable updateEveryNMillis.
Also some PEP8 updates
>  add script to flag updated datasets

- glider_dac/erddap/templates/private/dataset.deployment.xml
- scripts/build_erddap_catalog.py
set to True by default, however, check the latest file for the attribute and use that if it's set. Also use with statement when opening netCDF file. Previously left open.
> Add gts_ingest attr

- Dockerfile
Adds rsync to container in order to run syncing scripts.
> Adds rsync to container

- glider_dac/erddap/templates/private/dataset.deployment.xml
https://github.com/ioos/glider-dac/issues/156
> set accessibleViaFiles to true per dataset

- glider_dac/__init__.py
Initializes CSRFProtect prior to starting Flask app.  This will
hopefully address issues related to invalid CSRF tokens upon logging in
after application restarts on WebKit based browsers.
> Candidate fix for CSRF issues upon login

- glider_dac/templates/show_deployment.html
@benjwadams this solves the CSRF token issue when using drag & drop for uploading files
> Add CSRF token to headers

- config.yml
- docker-compose.yml
- glider_dac/views/deployment.py
- glider_dac_watchdog.py
- scripts/sync_erddap_datasets.py
> Use watchdog to update erddap datasets (realtime)

- scripts/build_erddap_catalog.py
Removes marks deployments listed in ERDDAP but not stored in the database as inactive
so that they can be properly removed.  Also flags dataset after marking as inactive in
datasets.xml so that ERDDAP removes the dataset.
> Mark deployments not found in DB but in ERDDAP as inactive

- scripts/build_erddap_catalog.py
Adds the qartod vars to the exclude list. They've already been added
> Fix erddap all variables logic

- glider_dac/glider_emails.py
- scripts/archive_datasets.py
Relaxes need for compliance check for archival and eliminates emailing of compliance check reports.
> Compliance check relax

- glider_dac/__init__.py
- scripts/build_erddap_catalog.py
- scripts/sync_erddap_datasets.py
- tests/resources.py
- tests/test_glider_qc.py
- tests/test_glider_xml.py
Adds unit tests for XML generation.  Checks the following cases:
1) Core variables are present before other variables
2) Other/non-core variables are alphabetized in a case-insensitive
fashion
3) No duplicate variable names are generated in the XML snippet
> Adds XML generation unit tests

- scripts/archive_datasets.py
Archives files using hard links rather than copying, saving a non-trivial amount of space.
> Hard link archive

- scripts/build_erddap_catalog.py
Fixes handling of ERDDAP dataset snippet generation.
- Don't generate empty snippet file upon encountering exception
- Update per-deployment timestamps rather than global timestamps to
prevent gliders from being skipped over when exception occurs in a
previous run and update_time is not altered.  Runs where an exception
occurs do not have their corresponding hash time updated in Redis.
> Fix ERDDAP dataset snippet handling

- docker-compose.yml
- glider_dac/glider_emails.py
- glider_dac/models/deployment.py
- glider_dac/templates/show_deployment.html
- requirements.txt
- scripts/archive_datasets.py
- scripts/dacUtils.py
Switches over to using JSON formatted compliance checker results and
storing as a field. Also requires NCEI data archival process to have no
standard name errors.
> Require standard names for archival

- glider_dac/models/user.py
Addresses https://github.com/ioos/ioosngdac/issues/166
> Create upload directory upon creation of user

- glider_dac/models/user.py
- glider_dac/templates/edit_user.html
Creates a unique key on username for user model and removes the username field from being edited post user creation.
> Enforce unique key on username, remove from edit fields

- scripts/build_erddap_catalog.py
@kerfoot Addresses https://github.com/ioos/ioosngdac/issues/169
> Perform rename operation on datasets.xml to atomically write

- Dockerfile
- glider_dac/templates/layout.html
- glider_dac_watchdog.py
Custom event handler logic for 2023 NAVOCEANO data submission.
> Navo inotify watch

- .github/workflows/sync_theme.yml
This action keeps the documentation website's theme up-to-date with the IOOS theme.
> adding workflow to sync theme

- _config.yml
- _config_dev.yml
This should get the site up again.
> should fix #214

- _config.yml
Closes https://github.com/ioos/glider-dac/issues/219
@kbailey-noaa is this OK? The NGDAC acronym is explained in the page summary, right below the title in the landing page.
> Shorten title

- docker-compose.yml
- glider_dac/__init__.py
- glider_dac/models/deployment.py
- glider_dac_watchdog.py
- requirements.txt
Adds QARTOD jobs to watchdog scripts when files are written.  Will likely result in much timelier QARTOD/QC runs on files.   Addresses #279.
> Event driven QARTOD

- requirements.txt
- scripts/replicatePrivateErddapDeployments.py
Supersedes #303 and implements update to `aiohttp` libraries.
> Update async web request requirements

- config.yml
- glider_dac/__init__.py
- requirements.txt
Uses Flask-Session, replacing older Flask-KVSession extension.  May fix some login related issues, including #295.  Requires that the config variable "SECRET_KEY" is set, or alternatively that app.secret_key is set.
> Use Flask-Session

- scripts/build_erddap_catalog.py
merging changes from the branch "Leilabbb patch build erddap xml w qartod vars" in to "Leilabbb-Implement-ioos-qc-flags
> merging branches

- data/qc_config.yml
- docker-compose.yml
- glider_qc/glider_qc.py
-- The glider_qc script has been modified to add functionality to check the arrays of time and the legacy variables
-- Other modifications were added to report on skipped processes or issues with the data arrays.
-- The qc_config was checked and the missing configuration specifications were added to help  complete the QC tests.
> update glider_qc.py and its dependency files

- glider_qc/glider_qc.py
- fixed string concatenation problem
- removed unnecessary logging info
> fixed a few malfunctions

- .github/workflows/md-link-check.yml
- .mlc_config.json
- README.md
We were missing the config file here and we also do not need to run this in the main branch, only gh-pages.
> Fix linkcheck GitHub Action

- .github/workflows/sync_theme.yml
Same as https://github.com/ioos/ioos-metadata/pull/46.
> keep sync_theme alive

- data/qc_config.yml
- tests/test_glider_qc.py
This came up in #367
- 1 - Changed the time array so the time_interval is in seconds and within acceptable thresholds.
- 2 - Changed the array being tested to have a distinct case of a flat line.
- 3 - Fixed the expected results to match the changes made in 1 and 2.
- 4 - Changed the flat_line thresholds to an acceptable standard.
> modified the test_units_qc

- glider_qc/glider_qc.py
- scripts/replicatePrivateErddapDeployments.py
- tests/test_glider_qc.py
Fixes a number of issues which were affecting QC throughput and archival of datasets.
> QC and replicate fixes

- glider_qc/glider_qc.py
- requirements.txt
Adds exception handling to location test.
Also updates `ioos_qc` version, and in turn `numpy` version, which results in less failures when running location test code for non-null and non-masked checks against `profile_lon` and `profile_lat`.
> Handle errors in location test

- glider_dac/glider_emails.py
- glider_dac_watchdog.py
- glider_qc/glider_qc.py
- scripts/build_erddap_catalog.py
- scripts/glider_qartod.py
Updates QC routines to remove some potential blocking/bottlenecks.
> QC task updates

- docker-compose.yml
> Update docker-compose.yml to use ERDDAP v2.25.1

- _docs/ngdac-netcdf-file-submission-process.md
Added text to the Deployment Creation section.
> explain deployment directory naming convention

- _docs/ngdac-netcdf-file-submission-process.md
Added more details about the gts_ingest requirement for sending data to GTS.
> explain the gts_ingest attribute

- _docs/ngdac-netcdf-file-format-version-2.md
> Update outdated and formerly broken IMOS manual link in docs

- _docs/ngdac-netcdf-file-format-version-2.md
I updated a broken link with what a link to what I think is the appropriate page.
> fixed broken link to the NetCDF Data Model webpage
